<?php

namespace Warehousing\WHBundle\Repository;

/**
 * LockedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockedRepository extends \Doctrine\ORM\EntityRepository
{
}
