<?php

namespace Warehousing\WHBundle\Repository;

/**
 * LogDescRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogDescRepository extends \Doctrine\ORM\EntityRepository
{
}
