<?php

namespace Warehousing\WHBundle\Repository;

/**
 * WarehouseLimitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseLimitsRepository extends \Doctrine\ORM\EntityRepository
{
}
